### ISSUE TITLE
Struggling to setup

### ISSUE THREAD

**Issue by mattpitts74** [jondbennett/Daylapse#2]
Hi There, Ive been trying to get your daylapse setup and got stuck at the Maketimelapse script bit.  I'm no expert at using raspberry pi and I don't know how to get it working.  I've done everything else in your instructions.  Are you able to clarify?  Thanks Matt

**Comment by jondbennett** [comment]
Hi Matt.
I looks like I left a file out. Let me get back to you.

**Comment by jondbennett** [comment]
Matt.
OK, I did not leave out a file, instead I referenced the wrong file in the README.md. Step five referenced a script named "MakeTimelapse". That was not correct. The correct script is "MakeFrames". That script carries out the operations (the bullet list) in step five.

Also, I would not use the Pi to make the actual movie, as it is probably not powerful enough. I just used it to take the images, then downloaded the images from the Pi and made the actual timelapse video on my desktop. I used "OpenShot" to make the movie.
Let me know if this helps.

**Comment by mattpitts74** [comment]
Thanks Jon, so much for coming back to me, I managed to run the MakeFrames script and got the following errors:  

Can't locate Image/Magick.pm in @INC (you may need to install the Image::Magick module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at ../timelapse-deflicker.pl line 23.
BEGIN failed--compilation aborted at ../timelapse-deflicker.pl line 23.
renaming  *.jpg  to  00000.jpg
mv: cannot stat '*.jpg': No such file or directory

**Comment by jondbennett** [comment]
Two things:
1) the "jpg" not found is probably because the MakeFrames script references "*.JPG". Just edit it and change the case. Also, you might want to remove the explicit cd to my home directory if you have not already.

2) On  the Pi, you might execute the following commands:

sudo apt install imagemagick
sudo apt-get install libimage-magick-perl


sudo cpan (if it asks to auto-configure say yes)
install File::Type
install Term::ProgressBar
install Image::ExifTool

**Comment by jondbennett** [comment]
Matt,
How is it going? Were you able to get Daylapse working?
